services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${X_MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=nocodb
      - MYSQL_USER=nocodb
      - MYSQL_PASSWORD=${X_MYSQL_NOCODB_PASSWORD:-nocodb}
      - LANG=C.UTF-8
    healthcheck:
      interval: 3s
      retries: 30
      start_period: 3s
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 3s
    restart: unless-stopped
    volumes:
      # - ./_docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./_docker/mysql/zz-zz.cnf:/etc/mysql/conf.d/zz-zz.cnf
      - mysql_data:/var/lib/mysql
  nocodb:
    image: "nocodb/nocodb:${X_NOCODB_VERSION:-latest}"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NC_DB: "mysql2://mysql:3306?u=nocodb&p=${X_MYSQL_NOCODB_PASSWORD:-nocodb}&d=nocodb"
    restart: unless-stopped
    volumes:
      - nocodb_data:/usr/app/data
volumes:
  mysql_data:
    driver: local
  nocodb_data:
    driver: local
