services:
  db:
    image: postgres:17.2-bookworm
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${X_POSTGRES_DB:-nocodb}
      POSTGRES_USER: ${X_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${X_POSTGRES_PASSWORD:-NOT_SAFE}
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 3s
      retries: 30
      timeout: 1s
    restart: unless-stopped
    user: ${X_UID:-1000}:${X_GID:-1000}
    volumes:
      - ./postgres/docker.conf:/etc/postgresql/docker.conf
      - ./_data/postgres:/var/lib/postgresql/data
  nocodb:
    image: "nocodb/nocodb:${X_NOCODB_VERSION:-latest}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NC_DB: "pg://db:5432?u=${X_POSTGRES_USER:-postgres}&p=${X_POSTGRES_PASSWORD:-NOT_SAFE}&d=${X_POSTGRES_DB:-nocodb}"
    restart: unless-stopped
    user: ${X_UID:-1000}:${X_GID:-1000}
    volumes:
      - ./_data/nocodb:/usr/app/data
